### ISSUE TITLE
Apple II Schematic power-up reset transistor error

### ISSUE THREAD

**Issue by reifsnyderb** [baldengineer/bit-preserve#124]
Nice job putting everything in KiCad!  I was thinking about doing the Apple II schematic and found you are already doing that.  That's a huge job!

I was studying your schematics and found that in the Apple II Schematic, Q5 (power-up reset transistor) is reversed.

Not a big deal as there's a lot of components, but I figured I'd let you know.

**Comment by baldengineer** [comment]
43fc6f1 Fixes it on the II+ schematic, pending fix on II schematic for future effort.
