### ISSUE TITLE
Thoughts on non-computer schematics?

### ISSUE THREAD

**Issue by martini1992** [baldengineer/bit-preserve#37]
I think this project is a fantastic idea and will prove in time to be a fantastic source of information for the community.

I have some schematics for an old Marantz amplifier that I have been looking to digitise for a few years, I saw this project and hoped you might be interested in adding it to your collection once they are done.

**Comment by baldengineer** [comment]
For now, I want to focus on computer-related schematics. If you create a repository for the amplifier, I'm open to having a document pointing people to other "retro" style repositories.
