### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by jgrip** [baldengineer/bit-preserve#50]
Right now this repository doesn't have a license defined.

Should there be a global license for all of the schematics or would it be preferable to have a per-schematic license?

Personally I'm fine with pretty much any open source/HW license.

**Comment by baldengineer** [comment]
I don't know what the right answer is. If I had thought about it more at the beginning, I would have picked a license like CC-BY-SA. But I don't know if that is fair to the work that others have done already.

I'm open to thoughts from others.

**Comment by jgrip** [comment]
CC-BY-SA is fine with me.

@Cumbayah @RobertBaruch @georgjz @StormTrooper @nicolas-robin What are your thoughts?

**Comment by StormTrooper** [comment]
I'm ok with CC-BY-SA

**Comment by georgjz** [comment]
CC-BY-SA is fine by me

**Comment by nicolas-robin** [comment]
I'm OK with CC-BY-SA

**Comment by RobertBaruch** [comment]
+1

**Comment by baldengineer** [comment]
Well, that was much easier than I expected. :) Thanks guys.

**Comment by Cumbayah** [comment]
Sure, let's go with CC-BY-SA.
