### ISSUE TITLE
Proposing the Inclusion of IBM and other ISA/Microchannel hardware. 

### ISSUE THREAD

**Issue by RTLV-Design** [baldengineer/bit-preserve#67]
Hello, 

I am quite the fan of IBM hardware and have been working to document and recreate many original cards and motherboards. I would be happy to contribute these to the project. 

-Rob

**Comment by baldengineer** [comment]
That sounds like a fantastic idea! Please feel free to contribute.  I look forward to seeing them!

P.S. Any chance you have a CGA card on your list?

**Comment by RTLV-Design** [comment]
The CGA card is actually my current project! I am still waiting for another revision of the card, as I have the original on hand. I have a lot of documentation to add as well.
