### ISSUE TITLE
Push Access?

### ISSUE THREAD

**Issue by RTLV-Design** [baldengineer/bit-preserve#71]
Sorry to be a thorn in your side :) 

Would it be possible to get push access? I have a bunch of datasheets that I can push to my PC-Compatibles directory.

**Comment by baldengineer** [comment]
What do you mean by datasheets?

**Comment by RTLV-Design** [comment]
Primarily the original datasheets with my notes on them. Such as the CGA documentation with the proper data lines traced out

**Comment by baldengineer** [comment]
Cleaning up old issues. I don't think using this repo to store PDFs makes sense.
