### ISSUE TITLE
Replacing footprints for obsolete parts with replacement parts.

### ISSUE THREAD

**Issue by qbancoffee** [baldengineer/bit-preserve#76]
I Finished the schematic for the Tandy TRS-80 coco2 26-302x making sure to include a footprint for each
component.

Most of the components use standard footprints so no issues there. 
However, K1 is a relay that is no longer made and I can't seem to find a pin compatible relay to replace it.

A workaround would be to create footprint for an electrically compatible relay so that the schematic can remain true
to the original one provided by Tandy.

I plan on making a PCB and I think I can make one with mostly new components using modified footprints but I don't want to create something that deviates from what you might have in mind. 
At least not in this branch..... 

The schematic has been completed and I believe that satisfies your intended goal so my question to you is.

Do you have reservations about changing footprints even though the schematic will still reflect the original?

**Comment by baldengineer** [comment]
Cleaning up issues, and I completely missed this one.

For the purpose of this archive, I don't think tracking footprints is critical. This is meant to be an archive of the schematics. 

Trying to extend the project to PCBs is going to make the archive unmanagable. 

That said, including footprint name/types in the schematic is fine.
